name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nau1/challenge-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy challenge-api-mliglyodka-tl --image=docker.io/nau1/challenge-api:latest --region=southamerica-west1 --platform=managed --allow-unauthenticated --port=8000