name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # Configurado desde tus secretos de GitHub
  GAR_LOCATION: southamerica-west1 # Como proporcionaste
  SERVICE: challenge-api # Asumiendo que este es el nombre del servicio
  REGION: southamerica-west1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Autenticación usando la clave de la cuenta de servicio
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Autenticación de Docker con Google Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'southamerica-west1-docker.pkg.dev'

      - name: Build and Push Container
          docker build -t "southamerica-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/challenge-api:latest" ./
          docker push "southamerica-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/challenge-api:latest"


      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/challenge-api:latest
