name: 'Continuous Integration'

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: make install

    - name: Run Model tests
      run: make model-test

    - name: Run API tests
      run: make test-api

